name: Run gen_json.py

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  run-gen_json:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python gen_json.py

      - name: Commit if it has changed
        env:
          ref: ${{ github.head_ref }}
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          git add Office_L.json
          git diff --staged --quiet || (git commit -m 'fix: run gen_json.py' && git push origin "HEAD:refs/heads/${ref}")
